### ISSUE TITLE
SSL connection failing due to optimisations in PR #134

### ISSUE THREAD

**Issue by Andy-Bell** [njh/ruby-mqtt#135]
Hitting an issue with this library due to #134, I now cannot get the client to load an SSL connection.

Ruby version 2.7.2.p137
Clean build of ruby with openssl 1.1.1i on OSX
Here is a minimal reproduction of the issue:
https://github.com/Andy-Bell/mqtt-error-from-pr-134

Expected outcome:
- MQTT client is created
- I can then listen for new messages

Current outcome
- Client hits an error and fails to create:
```
NoMethodError:
  undefined method `getbyte' for #<OpenSSL::SSL::SSLSocket:0x00007fc069f39298>
```

**Comment by njh** [comment]
Thanks for reporting this. 

I am not sure if the best thing to do is:
1) Just revert #134 
2) Attempt to monkey-patch `OpenSSL::SSL::SSLSocket`, so that it support #getbyte

What do you think @tenderlove ?

**Comment by tenderlove** [comment]
I think we should monkeypatch OpenSSL.  If normal sockets support `getbyte`, and SSLSocket doesn't, then I think it's a bug in SSLSocket.  I've sent a patch [upstream](https://github.com/ruby/openssl/pull/438).  I'll try making a patch for ruby-mqtt, but I might need a day or two.

**Comment by njh** [comment]
@tenderlove fantastic! Thank you very much!

**Comment by Andy-Bell** [comment]
Thanks both

**Comment by njh** [comment]
Hi @tenderlove. Do you think you have time work create a patch for the lack of `#getbyte` in ruby-mqtt?

Would be good to make a new release of this gem.

**Comment by tenderlove** [comment]
@njh I'm so sorry.  I totally forgot to do this.  I've done it and sent a PR #139 

🙇
