### PR TITLE
Backport OpenSSL::SSL::SSLSocket#getbyte

### LINKED ISSUE #135: SSL connection failing due to optimisations in PR #134
Hitting an issue with this library due to #134, I now cannot get the client to load an SSL connection.

Ruby version 2.7.2.p137
Clean build of ruby with openssl 1.1.1i on OSX
Here is a minimal reproduction of the issue:
https://github.com/Andy-Bell/mqtt-error-from-pr-134

Expected outcome:
- MQTT client is created
- I can then listen for new messages

Current outcome
- Client hits an error and fails to create:
```
NoMethodError:
  undefined method `getbyte' for #<OpenSSL::SSL::SSLSocket:0x00007fc069f39298>
```

### PR DESCRIPTION
**Pull request by tenderlove**
This backports the getbyte method which was added in this PR:

  https://github.com/ruby/openssl/pull/438

We only add the method to SSLSocket if the method isn't already defined.
I was able to test this with the following program:

```ruby
require 'rubygems'
require 'mqtt'

client = MQTT::Client.connect(
  host: "test.mosquitto.org",
  port: 8883,
  ssl: true
)

client.get
```

Fixes #135

### CODE REVIEW

**Comment by phlegx** [comment]
Hi @tenderlove!

I have openssl v2.1.2 installed with ruby v2.7.2 and ruby-mqtt main branch. I have also added the backport patch for OpenSSL. Connecting to the MQTT fails with the following error:

```
MQTT::ProtocolException: Failed to read byte from socket
/.../gems/ruby-2.7.2@test/bundler/gems/ruby-mqtt-8968969c50b0/lib/mqtt/packet.rb:223:in `read_byte'
/.../gems/ruby-2.7.2@test/bundler/gems/ruby-mqtt-8968969c50b0/lib/mqtt/packet.rb:30:in `read'
/.../gems/ruby-2.7.2@test/bundler/gems/ruby-mqtt-8968969c50b0/lib/mqtt/client.rb:466:in `receive_packet'
/.../gems/ruby-2.7.2@test/bundler/gems/ruby-mqtt-8968969c50b0/lib/mqtt/client.rb:273:in `block in connect'
```

Printing the bytes in method `getbyte` shows me that the last byte is always `nil`.

```
" "
"\x02"
"\x90"
"\x04"
"3"
"4"
nil
```

**Any idea why?**

Without backport patch and ruby-mqtt v0.5.0 all works fine.
